name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Este es el branch de producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Iniciar sesión en Docker Hub (o tu registro de contenedores)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir y subir la imagen Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: username/repository:latest  # Reemplaza con tu nombre de repositorio y tag

    # Configurar SSH para acceder al VPS
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Desplegar en el VPS usando SSH
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no user@your_vps_ip << 'EOF'
          docker pull username/repository:latest
          docker compose up -d --build
        EOF
